---

git_repo: https://github.com/yeti/chorelord-server
repo_name: chorelord-server

project_name: chorelord-server
application_name: chorelord-server

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDsv3UpcjNwbku6fbYGnnukq3HWeZ1qYa0c60jp6TrYrryhZG73PYViD8oGzq3bpEQ2Ppxltblj2a6U2Chw9ebcbSeJ2v9EBdgJK5IYv/iiJVj2F15/FKhe/h89KRvi+l6P8TjmvqYyJAbH170AyZk1HKLz2AMDLGveaakRHblo+p9NU9xRV0kp9ueAMYEHglzmHitjgF30bWlhmDFlELoqyBVSADEAYVaG4+k7jmJ1WzJb/TkaKhIrzs5HEafzleiNGfodUF8Q3qcToeeDl2a8fqbZBI0kV9ocmNUxF0LxYtrI+diyxjSiqgY2t9zYaxCeCjm+xP7dxbfrH3fJaPZVhGvwnMHWcpCT9HPycLRY71heZfrG1/IWKkNeXJyAWxmFVWwQh8q6d+rXvl+kwbsNVUu8Xf/zZ6hDaHmHu2KMQ+k8z+imMbM+BLcSJ7iotRFVJAc1UNhxyHYbrmyyeOC1qD+UNtZgyxeP0HHowOXBfSZQyXuvlUnzMJGH+mkT7mOVqHb6jtOxSRxQp7UtXmYyW13f/7avRKzlcWDQWqQ1X5Ke/Hd07IxmjsqZefGCy2eLE2dK9CJYNMby5+W5Z5mkr5rKVnv8UrXqwGaxBE1UeOZRDJWoUUzwKdb7jQgdK2sfU4H/v750b1gBoRJS5/QEa8z4TYXNQeHonFrMW79thw==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJJwIBAAKCAgEA7L91KXIzcG5Lun22Bp57pKtx1nmdamGtHOtI6ek62K68oWRu
  9z2FYg/KBs6t26RENj6cZbW5Y9mulNgocPXm3G0nidr/RAXYCSuSGL/4oiVY9hde
  fxSoXv4fPSkb4vpej/E45r6mMiQGx9e9AMmZNRyi89gDAyxr3mmpER25aPqfTVPc
  UVdJKfbngDGBB4Jc5h4rY4Bd9G1pYZgxZRC6KsgVUgAxAGFWhuPpO45idVsyW/05
  GioSK87ORxGn85XojRn6HVBfEN6nE6Hng5dmvH6m2QSNJFfaHJjVMRdC8WLayPnY
  ssY0oqoGNrfc2GsQngo5vsT+3cW36x93yWj2VYRr8JzB1nKQk/Rz8nC0WO9YXmX6
  xtfyFipDXlycgFsZhVVsEIfKunfq175fpMG7DVVLvF3/82eoQ2h5h7tijEPpPM/o
  pjGzPgS3Eie4qLURVSQHNVDYcch2G65ssnjgtag/lDbWYMsXj9Bx6MDlwX0mUMl7
  r5VJ8zCRh/ppE+5jlah2+o7TsUkcUKe1LV5mMltd3/+2r0Ss5XFg0FqkNV+Snvx3
  dOyMZo7KmXnxgstnixNnSvQiWDTG8ufluWeZpK+aylZ7/FK16sBmsQRNVHjmUQyV
  qFFM8CnW+40IHStrH1OB/7++dG9YAaESUuf0BGvM+E2FzUHh6JxazFu/bYcCAwEA
  AQKCAgA2ggpGpZ2ESFC1OlZbhcev7S1DlTKSGLUT0HQ0Lte2pdyWSBpoYEjCgCIi
  mRlcVaDC4H1/yWxKugbBDFebUnJ508PjsIFPNw07Z0W23xQuuOyXlF/UYHw3isjE
  ex+Jjd2RxJc2QTTgnHzXLCu+76uPl+1IuTZQV7zqM2eSokZbDkD5O9KhA7i7qbY5
  RKyRfwlGjjGtMhPvv/UgXDsbKtPCH9kQzSx7Cu4yFm1PogO3Q2z/0vh/tqoCXhYO
  NNl3cs9dFVsJvsR0jN7o3UEBgi1MPtjJZIvejz+Pj/yd1d4612jKFwQ2fP4HaaAO
  nxyA03269V3AN3j6tJgY0WDyBXGZY4miTZ00sHGQ+DLR3HRqH1LsqO4xbmiK9Xmx
  AF7/GgLZG9JXNIV0av87Fk9+O+PIPjxtrDLBYO4C/83zSUw078papwuDkA29Eu9K
  sE0RndYaUd1MOwnxV/3/0fzdAgFiRCAjXpGMnGy+tJ5Ew3bLyX294BpO2V8HuZl3
  5LBliHxEs+USRc3nVdZ/PyqjtIFfAtm2FOi/P3kVtFvTZAZ+muuwl3TgbIZTEeRO
  BTSdgXritcgcdjUoSSk/7zZegHjoZMjx2HCIOInga8q24//j32QnLxBPjewycNOQ
  Da4zziHDG2TFMf1SKrVQvJskzF7AWEnawZCq9W4xkpjheVe6IQKCAQEA80yyAKea
  JxI5duejP/RLwvZvYQsnv8wQwdJ55LC3yvS1rXTMojZUXPNrbtaFpEF1RkhG/mbd
  yRSW+C/p4Z2skmHG5vlp/N/pjlvtBIy1ourxlekk1PLsuh8KSN4klOqzDSX+hriZ
  wdGNm0b7ySfl55mKS6w4fjNPW2WCAiyv1Tij5/eeHtKySK8NSiHwe4EeOFjG3Y00
  YxQ8MYOK2abiT5BF7QUMgkSF1u5Q5a377RKHYC4d9KS++tnD5UFaT0DVwfuTNWnh
  ua/Pkk1VasOK3N3zhLj/d+riWu5+qx3H9mYYNHD+tL0fIw/oz/AF8pxduDnOeelj
  bQCLeNjDKGz7MQKCAQEA+Rs1mLwNVsWJKvpmlPa0xJnJOLOoUEoaAR+8aSBwGim/
  CPhIYM8869Ltg7rsqzEUO4VaDCs8nNb2QsTFcfIZ52Qp7etxAwrKJOEMEYxRWkKe
  H1GoCRoF5Z2qqvQC0oe+V85QrNw3wj9scVAGGVMngI3SLwRmYlWvGrqy882ICMgu
  mzFu8xSJ325HmIRYB4pEkis9KKEFEMpERvsnIyK08wa3Z+H6c6IgeQdt9qw6msz+
  qrWeBSWSD6wMriVvytbZ3AoXKKGS/L+URaVDzSK0S6FfOUAE2hDdjniiDQWJvsHJ
  mZjS6qAU1/i0mZ+NwoC/Zz3Ogiq/0EerM+xgrGNWNwKCAQA3PoX4khX1ozS7JBO0
  dOMzDMPzlBXdfheb+w/Edr/07KXIEgpZFt8HEBqn2zwTNO3NHKJKJ89aVjuFdVO0
  8Bl8T4lbbuy7B5i/w23JJ64ipRhgAsVjORm5lUy/iPljevtXE/Z8XrRDBzMRPAf2
  AAI7GWkGj79wIHR3e1AO8FiooKjPBjG4K/1hdaYd3CD/2iyjfL0DF4n6qWCVmZnQ
  nA0tJcRK8meJuMdvK0PhMyVOCnQEydPxdesLiKDrkHBSKJWg61/ctAMWJ66JONgZ
  WvdP+XHPBDa14vas0RSgBC4ga8Q5PCMJpRvJ2VXyyTyAfzLknvOcSPtTh9kjgoyl
  xEExAoIBAFwh6yXNT6WrM7tYl3467MrWEi1NjU/8yDdoNHgxTiTvEb/QjHx5yY9z
  GPOivAvpABGvlYlwqF9dxgEV4+zr3RbO3g8oCElWwUL4lU0cN66JexAcVGjhXhL5
  yHin/S8+k3DIVuBIJrtKV+Jk9YyCS9bpHTbUisWN6VCagrtXZhvRZiNyGhX/n6qq
  kAJh2GkZg5kIMvuG6me2V6BlHamKGaDU+BqM4uPHr/jzfYFBW/+LGBmtSH+g0K/J
  M3tpTzqXUkZm2P/nGoUumjlUEYqablKWobB79A9vM3KRPWZRiQurgtOzSTcL9AmY
  67rx3y10DtaxbmKISx9OkoyGvY6kwusCggEAGalF2Tr6h/jwV6fRNQlOZClz6m30
  uKpWo9jG7zppME5SOUeuMy2BsT5qDALEdVqB98K9Tmtj2njFpPdipobiGsJZxrsZ
  y6p3j4M1yRpuQDCUas7h+6ghu26/+SHguEvXTeX8AUqeHaT2yCc9bsd7tH0jhr4G
  l77nJseTdtGXMQcG7AQ7o8D3IMbgrBoUxuwsJ1uCG3asba/KCtmNe1M/hjmaJCO2
  UA7sgTdqUq7kAJQODaVOSLCS9iCVXv8SKC5KZM0qD5wT1qvTu5++vcgZcy5+L019
  YsiYLSMpXTnRVCd0bCbxVJxc3zfDxJMs60ivNDTiggHuV0rFQHjQl/dazA==
  -----END RSA PRIVATE KEY-----

